FROM almalinux:9.8

# Add required system packages 
# generic and pyenv installation
RUN dnf -y install git gcc
# Required for python2 installation
RUN dnf -y install patch zlib-devel readline-devel bzip2-devel sqlite-devel openssl-devel
# Required for python3 installation
RUN dnf -y install libffi-devel xz-devel

RUN dnf -y update

# Environment and folder creation
## Dir for course specific material
ENV TOOLSDAY_OPTDIR=/opt
## Dir for all downloads
ENV TOOLSDAY_DOWNLOADDIR=${TOOLSDAY_OPTDIR}/download
RUN mkdir ${TOOLSDAY_DOWNLOADDIR}
## Dir for all sources, a subfolder for each source tree
ENV TOOLSDAY_SOURCEDIR=${TOOLSDAY_OPTDIR}/source
RUN mkdir $TOOLSDAY_SOURCEDIR
## Dir for all builds, a subfolder for each build environment
ENV TOOLSDAY_BUILDDIR=${TOOLSDAY_OPTDIR}/build
RUN mkdir $TOOLSDAY_BUILDDIR
## Dir for all binaries, a subfolder for each software
ENV TOOLSDAY_APPSDIR=${TOOLSDAY_OPTDIR}/apps
RUN mkdir ${TOOLSDAY_APPSDIR}
## Dir for all scripts
ENV TOOLSDAY_SCRIPTSDIR=${TOOLSDAY_OPTDIR}/scripts
RUN mkdir ${TOOLSDAY_SCRIPTSDIR}
## Dir for sharing data with host
ENV TOOLSDAY_SHAREDIR=${TOOLSDAY_OPTDIR}/share
RUN mkdir ${TOOLSDAY_SHAREDIR}

# Install pyenv
RUN git clone https://github.com/pyenv/pyenv.git $TOOLSDAY_SOURCEDIR/pyenv
# build pyenv
RUN cd $TOOLSDAY_SOURCEDIR/pyenv && src/configure && make -C src
# Add env var
ENV PYENV_ROOT=$TOOLSDAY_SOURCEDIR/pyenv
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
# Should initialize pyenv user env
#RUN eval "$(pyenv init - bash)"

# Installing python distributions using pyenv
RUN pyenv install 2.7.18
RUN pyenv install 3.14.7

# Copy content from git folders
ADD scripts/* ${TOOLSDAY_SCRIPTSDIR}/

# Run python2 installation script
RUN ${TOOLSDAY_SCRIPTSDIR}/setuppython2.sh
# Run python3 installation script
RUN ${TOOLSDAY_SCRIPTSDIR}/setuppython3.sh

# When the container is started, start a login shell that requires a command
# This is to be able to pass commands to the container without logging 
# in, in an environment that can also be initialized by scripts
ENTRYPOINT ["/bin/bash","-l","-c"]
